using System.Text.Json;
using System.Text.Json.Serialization;
using DnaEntropyGraph.Core.Inputs;
using Shouldly;
using Xunit;

namespace DnaEntropyGraph.Core.Tests.Inputs;

/// <summary>
/// THE decisive test for issue #64: every case in
/// <c>tests/contract-fixtures/cli_validate_parity.json</c> (a golden vector captured from
/// the real `dna-entropy validate` CLI, per that file's own provenance note) is replayed
/// against <see cref="SequenceValidator" /> and must produce byte-identical output to what
/// the Python worker produced - not a hand-written expectation, so the C# port has
/// something outside itself to be wrong against. A change to <see cref="SequenceValidator" />
/// that silently changes wording, position arithmetic, or the pass/fail verdict for any of
/// these cases fails this test; the fixture is read-only (never edited to make a case pass).
/// </summary>
public sealed class SequenceValidatorParityTests
{
    // Matches the CLI `validate` command's own default (`DEFAULT_MAX_TOTAL_LEN` in
    // worker/src/dna_entropy/config.py, wired through as --max-len's typer default) - NOT
    // SequenceValidator.DefaultMaxLen, which mirrors validate_sequence's own narrower
    // function-signature default (the per-window cap). None of the fixture's cases pass
    // --max-len, so every case exercises this CLI-level default.
    private const int CliDefaultMaxLen = 10_000_000;

    public static IEnumerable<object[]> Cases()
    {
        var json = File.ReadAllText(ContractFixtures.Path("cli_validate_parity.json"));
        var fixture = JsonSerializer.Deserialize<FixtureFile>(json) ?? throw new InvalidOperationException("empty fixture");
        foreach (var c in fixture.Cases)
        {
            yield return [c];
        }
    }

    /// <summary>
    /// A Theory whose data source yields nothing passes, and a parity test that
    /// quietly stops replaying anything is worth less than no test at all: it
    /// advertises coverage that is not there. This asserts the fixture is
    /// non-empty and names every case it carries, so the count cannot shrink
    /// unnoticed. It deliberately asserts "at least one", not "exactly five":
    /// a fixture that GAINS cases should not turn this red (see
    /// <c>an-assertion-that-encodes-a-temporary-fact</c>).
    /// </summary>
    [Fact]
    public void The_fixture_actually_carries_cases_a_vacuous_theory_would_hide()
    {
        var cases = Cases().ToList();

        cases.ShouldNotBeEmpty(
            "cli_validate_parity.json yielded no cases, so every parity assertion above "
            + "is being skipped silently.");
    }

    [Theory]
    [MemberData(nameof(Cases))]
    public void Matches_the_real_worker_cli_byte_for_byte(FixtureCase testCase)
    {
        var rna = testCase.Args.Contains("--rna");
        var raw = ResolveInputText(testCase);

        string actualOutput;
        try
        {
            var result = SequenceValidator.Validate(
                raw,
                maxLen: CliDefaultMaxLen,
                rna: rna,
                minLen: SequenceValidator.DefaultMinLen,
                ambiguityPolicy: AmbiguityPolicy.Error); // the CLI `validate` command never passes a policy through - see class docs
            actualOutput = string.Concat(result.Notices.Select(n => $"  - {n}\n")) + $"OK: valid sequence, {result.Length} nt\n";
            testCase.ExitCode.ShouldBe(0, $"case {testCase.Id} expected exit {testCase.ExitCode} but the C# port accepted the input");
        }
        catch (SequenceValidationException ex)
        {
            SequenceValidationException.ErrorCode.ShouldBe("INPUT_INVALID"); // docs/contract/error-codes.json
            actualOutput = $"ERROR: {ex.Message}\n";
            testCase.ExitCode.ShouldBe(1, $"case {testCase.Id} expected exit {testCase.ExitCode} but the C# port rejected the input: {ex.Message}");
        }

        actualOutput.ShouldBe(testCase.Output, $"case {testCase.Id} diverges from the golden vector");
    }

    private static string ResolveInputText(FixtureCase testCase)
    {
        var iIndex = testCase.Args.IndexOf("-i");
        if (iIndex < 0)
        {
            iIndex = testCase.Args.IndexOf("--input");
        }
        if (iIndex >= 0 && iIndex + 1 < testCase.Args.Count)
        {
            // The fixture was captured with the worker's own cwd at `worker/` (its
            // provenance note: generated by CliRunner against that checkout); the relative
            // path recorded is relative to that directory.
            var relative = testCase.Args[iIndex + 1];
            var path = System.IO.Path.Combine(ContractFixtures.RepoRoot, "worker", relative.Replace('/', System.IO.Path.DirectorySeparatorChar));
            return TextDecoder.ReadText(path);
        }
        return testCase.Stdin ?? string.Empty;
    }

    public sealed class FixtureFile
    {
        [JsonPropertyName("cases")]
        public List<FixtureCase> Cases { get; set; } = [];
    }

    public sealed class FixtureCase
    {
        [JsonPropertyName("id")]
        public string Id { get; set; } = "";

        [JsonPropertyName("args")]
        public List<string> Args { get; set; } = [];

        [JsonPropertyName("stdin")]
        public string? Stdin { get; set; }

        [JsonPropertyName("exit_code")]
        public int ExitCode { get; set; }

        [JsonPropertyName("output")]
        public string Output { get; set; } = "";

        public override string ToString() => Id; // xUnit theory display name
    }
}
